# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Run Database
        run: |
            cd Docker/
            docker-compose up -d --build
      - name: Sleep for 10 seconds
        uses: jakejarvis/wait-action@master
        with:
           time: '10s'
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v1.5
        with:
            url: http://localhost:6060
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify
